### ISSUE TITLE
Implement helper in utils near `execute-process` to parse an object to command line arguments

### ISSUE THREAD

**Issue by BioPhoton** [flowup/quality-metrics-cli#43]
# Motivation

Plugin authors can already use our `executeProcess` function in their code to writ plugins faster.
The helper `objectToCliArgs`  helps to create an array of command line arguments from a object in the common standard e.g. `--param`, `--no-param` etc...

This helps library authors to execute their code and avoids errors. The function should be used separately from the `executeProcess` function to have more flexibility.

# Usage in a custom plugin

In custom plugins the function is most useful for runner arguments:

```typescript
export async function myPlugin(config?: NxValidatorsPluginConfig) {
  const { outputPath } = config || {};
  return {
    // ...
    runner: {
      command: 'node',
      args: objectToCliArgs({ _: 'bin.js', interactive: false }),
      outputPath: 'out.json'
    },
    // ...
  };
}
```

# Todos
- [ ] implement the logic
- [ ] implement tests
- [ ] document it with JS docs 
- [ ] export it as public API
