### ISSUE TITLE
Nx plugin setup

### ISSUE THREAD

**Issue by matejchalk** [flowup/quality-metrics-cli#9]
# Motivation

As all the good stuff will come from the community plugins it pays of to give them the best DX possible.
Next to good docs and examples etc i see a Nx plugin very useful as it can support us in the following areas:
- skufholding
  - setup
  - unit testing 
  - e2e testing
- migration
- publishing
- integration 
- documentation
- we could leverage the power of Nx CLI

This should make it as easy as possible to start a custom plugin project.

The plugin can also help use with advertisement as:
- we can generate branded readme files etc with the generate commands
- we can publish it under Nx community plugins

# Todos
- [x] Basic setup for Nx plugin package
- [ ] Execute command `collect` to
  - [ ] execute the CLI
  - [ ] maintaining configurations partially in `project.json`
- [x] Generate command `init` to
  - [ ] setup code pushup in a specific project
- [ ] Generate command `plugin` to create a custom plugin inc:
  - [ ] project with `esbuild` & vitest` setup for the plugin logic
  - [ ] project with `vitest` setup for the plugin e2e tests

**Comment by kikaflowup** [comment]
@BioPhoton please create more smaller issues from this one.

**Comment by BioPhoton** [comment]
done
